---
Name: subsite-extras
After: 
- 'fluent/*'
- 'subsites/*'
Only:
  classexists: 'Subsite'
---
Director:
  rules:
    'admin/security/autocomplete/$ID': 'SubsiteSecurityAutocompleter'
SubsiteExtension:
  admin_default_permissions:
    ['CMS_ACCESS_CMSMain','CMS_ACCESS_AssetAdmin','EDIT_SITECONFIG', 'SITETREE_VIEW_ALL', 'SITETREE_EDIT_ALL','VIEW_DRAFT_CONTENT']
Subsite:
  extensions:
    - SubsiteExtension
Security:
  extensions:
    - SubsiteLoginExtension
SubsiteAdmin:
  extensions:
    - SubsiteAdminExtension
AssetAdmin:
  extensions:
    - SubsiteAssetAdminExtension
---
Only:
  classexists: 'Fluent'
---
SiteTree:
  extensions:
    - FluentSiteTreeSubsiteFix
LeftAndMain:
  extensions:
    - FluentLeftAndMainSubsite